config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources  :albums do 
    resources :reviews 
  end 
  root 'albums#index'
  
  
  
end

app/models/album.rb
class Album < ActiveRecord::Base
    belongs_to :user
    belongs_to :category 
    has_many :reviews 
    
   	has_attached_file :album_img, :styles => { :album_index => "250x350>", :album_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :album_img, :content_type => /\Aimage\/.*\Z/
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :albums 
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :album
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :albums 
  has_many :reviews 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :find_album, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]
    
    def index
        if params[:category].blank?
         @albums = Album.all.order("created_at DESC")  
     else
         @category_id = Category.find_by(name: params[:category]).id
	     @albums = Album.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    
    def show 
    end 
    
    
    def new
        @album = current_user.albums.build 
        @categories = Category.all.map{ |c| [c.name, c.id]} 
    end
    
    def create 
        @album = current_user.albums.build(album_params)
        @album.category_id = params[:category_id]
        
		if @album.save
			redirect_to root_path
		else
			render 'new'
		end
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id]}
    end
    
    def update
        @album.category_id = params[:category_id]
        
		if @album.update(album_params)
			redirect_to album_path(@album)
		else
			render 'edit'
		end
    end
    
    def destroy
        @album.destroy
        redirect_to root_path
    end

    private
    
    def album_params
        params.require(:album).permit(:title, :info, :artist, :category_id, :album_img)
    end
    
    def find_album 
        @album = Album.find(params[:id])
        
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_album
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]


	def new
		@review = Review.new
	end
    
    #render is there to save the comment if refreshed 
	def create
		@review = Review.new(review_params)
		@review.album_id = @album.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to album_path(@album)
		else
			render 'new'
		end
	end

	def edit
	    @review = Review.find(params[:id])
	end

	def update
		if @review.update(review_params)
			redirect_to album_path(@album)
			else
				render 'edit' 
		end
	end

    def destroy
	@review.destroy
	redirect_to album_path(@album)

    end

	private

	def review_params
			params.require(:review).permit(:rating, :comment)
	end

	def find_album
			@album = Album.find(params[:album_id])
	end

	def find_review
		@review = Review.find(params[:id])
	end
	
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album do |f| %>
<%= f.file_field :album_img %></br>
<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category") %>
  <%= f.input :title %>
  <%= f.input :info %>
  <%= f.input :artist %>
  <%= f.button :submit %>
<% end %>

app/views/albums/edit.html.erb
<div class= "ol-md-10 col-md-offset-1">
<div class="new-album-form">


<h1>Edit Album </h1>

<%= simple_form_for @album, html: {multipart: true} do |f| %>
 <%= f.file_field :album_img %></br>
 
<%= f.select :category_id, @categories %></br> 
  <%= f.input :title %>
  <%= f.input :info %>
  <%= f.input :artist %>
  <%= f.button :submit %>
<% end %>
</div>
</div>

app/views/albums/index.html.erb
<h1.class="current-category"><%= params[:category] %></h1>

<% if @albums.count == 0 %>
	<h3>There are no Albums here </h3>
<% else%>
<div class="row">
	<% @albums.each do |album| %>
	<div  class="col-md-3">
	    <a href="/albums/ <%= album.id %>">
	        <%= image_tag album.album_img.url(:album_index), class: "album" %>
	    </a>
	    </div>
<% end %>
</div>
<% end %>

app/views/albums/new.html.erb
<div class= "ol-md-10 col-md-offset-1">
<div class="new-album-form">

<h1>New album</h1>
<p><em>Enter album details below</em> </p>
<%= render 'form' %>

</div>
</div>

app/views/albums/show.html.erb
<div class="row">
  <div class="col-md-4">
	<%= image_tag @album.album_img.url(:album_show), class: "album-show"%>
  </div>
  <%-# this is where the image and description goes -%>
	<div class="col-md-8">
		<div class="album-info">
		<h1 class="album-title"><%= @album.title %></h1>
		<h3 class="album-artist"><span><em>From: </em></span><%= @album.artist %></h3>
		<h4 class="album-artist"><%= @album.category.name %></h4>
		<h4 class="avg-rating">Average Rating</h4>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span class="number-of-reviews"><em>From: </em><%= @album.reviews.count %> reviews </span>
		<p class="album-desc"><%= @album.info %></p>
		</div>
	</div>
	
</div>

 <%-# this is the styling and review secion and link to add review (paths)-%>
<div class="row">
	<div class="col-md-12">
		<div class="reviews">
						<h1> Reviews </h1>
							<%= render @album.reviews %>
		 			<div>
		 					<%= link_to "Add Reviews", new_album_review_path(@album), class: "btn-custom"%>
		 			</div>
		</div>
	</div>
</div>
 
 
 <%-# Links for edit and delete -%>
 <div class="links btn-group">
<% if user_signed_in? %>
<% if @album.user_id == current_user.id %>
		<%= link_to "Edit", edit_album_path(@album), class: "btn btn-custom" %>
		<%= link_to "Delete", album_path(@album), method: :delete, data:
		 {confirm: "Are You Sure" }, class: "btn btn-custom" %>
	<% end %>
<% end %>
</div>

 <%-# JQuery scripts  -%>
<script>
	$('.review-rating').raty({
		readOnly: true, 
		score: funtion() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlbumRatingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  	<nav class="navbar navbar-default">
		<div class="container">
				<div class="navbar-header">
					<%= link_to "AlbumRatingApp", root_path, class: "navbar-brand" %>
				</div>

			<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>

			<% else %>
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<li><%= link_to "Log In", new_user_session_path %></li>

			<% end %>
			</ul>
			
			<ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Genre <span class="caret"></span></a>

				<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
					<li class="<%= 'active' if params[:category] == category.name %>">
							<%= link_to category.name, albums_path(category: category.name), class: "	link " %>
					</li>
						<% end %>
				</ul>

				</li>

          <% if user_signed_in? %>
	    	<li><%= link_to "Add Album", new_album_path %></li>
	    	<%end%>
    	</ul>
</div>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@album, @album.reviews.build]) do |f| %>
	<div id="rating-Form">
	<label> Rating </label>
	</div>
	<%= f.input :comment %>
	<%=  f.button :submit, :class => "btn-custom2" %>
<% end %>

<script>
	$('#rating-form').raty({	
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>
	
	<% if user_signed_in? %>
		<% if review.user_id == current_user.id %>
			<div class="links btm_group">
				<%= link_to "Edit", edit_album_review_path(review.album, review), 
				class: "btn btn-custom" %>
				<%= link_to "Delete", album_review_path(review.album, review),
				method: :delete, data: { confirm: "Are you sure?"},
				class: "btn btn-custom "%>
			</div>
		<% end %>
	<% end %>
</div>
  

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="edit-review-form">
        <h1> Edit Review </h1>
    
            <%= simple_form_for([@album, @review]) do |f| %>
        	<div id="rating-Form"
        	<label> Rating </label>
        	</div>
	        <%= f.input :comment %>
	        <%= f.button :submit, :class => "btn-custom2" %>
            <% end %>
        </div>
     </div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
<div class="new-review-form">
<h1> Post review </h1>
	<%= render 'form' %>
</div>
</div>
 